version: '3.8'
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: "Developer"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - midbnet

  backend:
    build: .                      
    container_name: ecommerce_be_backend
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: Server=sqlserver2022,1433;TrustServerCertificate=True;User Id=sa;Password=${DB_PASSWORD};Database=master;Encrypt=True;Connection Timeout=30;
    networks:
      - midbnet

volumes:
  sqlserverdata:

networks:
  midbnet:
    driver: bridge
    name: midbnet
